### ISSUE TITLE
Demo Cannot Run

### ISSUE THREAD

**Issue by yotofu** [Jarrome/Uni-Fusion#1]
Can not run the demo successfully  with the data when i run "python demo.py configs/replica/office0.yaml"

**Comment by Jarrome** [comment]
can you please share me the error message pls?

**Comment by yotofu** [comment]
![image](https://github.com/Jarrome/Uni-Fusion/assets/24996527/8a42973b-420b-49cf-a59a-4bad6d3af61e)
![image](https://github.com/Jarrome/Uni-Fusion/assets/24996527/a793534d-6c83-4309-87af-7c1f78f7b235)
![image](https://github.com/Jarrome/Uni-Fusion/assets/24996527/bf993adc-01db-44a2-8a7e-3a856f18fafc)
I download the data, and run python demo.py conifgs/replica/office0.yaml,  it fails

**Comment by Jarrome** [comment]
Really thank you for sharing the error!
 This problem should be from combining with other scripts...
 
Because this first demo doesnot really use ir, saliency and style properties.
So a fast fix is just comment that line.

In this weekend, I will check and fix this bug. 

And maybe provide a several-lines toy example if I get spare time.

**Comment by Jarrome** [comment]
Hi, yotofu,

I have checked and clear bugs. 

Besides, I also provide a [toy example](https://github.com/Jarrome/Uni-Fusion/blob/main/README.md#0-quick-try)  for quick try.

Thank you for contributing issue.

Enjoy Uni. :D

Yijun
